config/routes.rb
Rails.application.routes.draw do
  #new, create, edit, destroy, index, show, update
  #may need to nest some routes
  root to: 'sessions#new'
  resources :users
  resource :session, only: [:new, :create, :destroy]
  resources :children, only: [] do
    resources :posts, only: [:new, :edit, :index]
  end
  resources :posts, except: [:new, :edit, :index]
  resources :comments, except: [:index, :show]
  resources :children
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string           not null
#  email           :string           not null
#  name            :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime
#  updated_at      :datetime
#  admin           :boolean          default("false")
#

class User < ActiveRecord::Base
  validates :username, :password_digest, :email, presence: true, uniqueness: true
  validates :name, presence: true
  validates :password, length: { minimum: 6, allow_nil: true}
  validates :password2, length: { minimum: 6, allow_nil: true}
  validate :check_password

  after_initialize :ensure_session_token
  attr_reader :password, :password2

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :children

  def self.generate_session_token
    begin
      token = SecureRandom.urlsafe_base64
    end until !self.exists?(:session_token => token)
    token
  end

  def self.find_by_credentials(email, password)
    @user = self.find_by_email(email)
    if @user.nil? || !@user.is_password?(password)
      @user = nil
    end
    @user
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def password2=(password2)
    @password2 = password2
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
    self.session_token
  end

  private
  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end

  def check_password
    unless @password == @password2
      errors.add(:check_password, "passwords did not match")
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_current_user!, except: [:create, :new]

  def index
    render :index
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login!(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def new
    @user = User.new
    render :new
  end

  def edit
    @user = User.find(params[:id])
    render :edit
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      User.new(user_params.merge(id: params[:id]))
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.id == current_user.id
      logout!
      @user.destroy
      redirect_to new_session_url
    else
      @user.destroy
      render :index
    end
  end

  def show
    @user = User.find(params[:id])
    render :show
  end
end

app/views/users/_form.html.erb
<% if @user.persisted? %>
  <% verb = "Update" %>
  <% url = user_url(@user) %>
  <% button_val = "Update #{@user.name}" %>
<% else %>
  <% verb = "Create" %>
  <% url = users_url %>
  <% button_val = "Create account" %>
<% end %>
<form action="<%= url %>" method="POST">
  <%= csrf_input %>
  <% if @user.persisted? %>
    <input type="hidden" name="_method" value="PATCH">
  <% end %>
  <label for="username_field">Username:</label>
  <input type="text" id="username_field" name="user[username]" value=<%= @user.username %>>
  <br>
  <label for="email_field">Email:</label>
  <input type="text" id="email_field" name="user[email]" value=<%= @user.email %>>
  <br>
  <label for="name_field">Name:</label>
  <input type="text" id="name_field" name="user[name]" value=<%= @user.name %>>
  <br>
  <% unless @user.persisted? %>
    <label for="password_field">Password:</label>
    <input type="password" id="password_field" name="user[password]">
    <br>
    <label for="password2_field">Confirm Password:</label>
    <input type="password" id ="password2_field" name="user[password2]">
    <br>
  <% end %>
  <input type="submit" value="<%= button_val %>">
</form>
<% if @user.persisted? %>
  <%= link_to @user.name, user_url(@user), method: :get %>
<% else %>
  <%= link_to "Log In Page", new_session_url, method: :get %>
<% end %>

app/views/users/edit.html.erb
<h1>Edit <%= @user.name %></h1>
<%= render partial: "form" %>

app/views/users/index.html.erb
<h1>All the users!</h1>
<ol>
  <% User.all.each do |user| %>
    <li>
      <%= link_to user.username, user_url(user) %>
      <% if current_user.admin %>
        <%= button_to "Delete", user_url(user), method: :delete %>
      <% end %>
    </li>
  <% end %>
</ol>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>
<h3>Username: <%= @user.username %></h3>
<h3>Email: <%= @user.email %></h3>
<h3>Name: <%= @user.name %></h3>
<% if !current_user.nil? && @user.id == current_user.id %>
  <%= button_to "Edit #{@user.username}", edit_user_url(@user), method: :get %>
  <%= button_to "Delete #{@user.username}", user_url(@user), method: :delete %>
<% end %>
<%= button_to "Index", users_url, method: :get %>