config/routes.rb
Rails.application.routes.draw do
  #new, create, edit, destroy, index, show, update
  #may need to nest some routes
  root to: 'sessions#new'
  resources :users
  resource :session, only: [:new, :create, :destroy]
  resources :children, only: [] do
    resources :posts, only: [:new, :edit, :index]
  end
  resources :posts, except: [:new, :edit, :index]
  resources :comments, except: [:index, :show]
  resources :children
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  content    :string           not null
#  user_id    :integer          not null
#  child_id   :integer          not null
#  picture    :string           not null
#  created_at :datetime
#  updated_at :datetime
#

class Post < ActiveRecord::Base
  validates :content, :user_id, :child_id, :picture, presence: true
  # validate :picture_size
  belongs_to :user
  mount_uploader :picture, PictureUploader
  belongs_to :child
  has_many :comments, dependent: :destroy

  private

  def picture_size
    if picture.size > 5.megabytes
      errors.add(:picture_size, "should be less than 5MB")
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_current_user!
  before_action :require_owner!, only: [:edit, :update, :destroy]

  def new
    @post = Post.new
    render :new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to child_posts_url(@post.child)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def edit
    @post = Post.find_by_id(params[:id])
    render :edit
  end

  def update
    @post = Post.find_by_id(params[:id])
    if @post.update(post_params)
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :edit
    end
  end

  def show
    @post = Post.find_by_id(params[:id])
    render :show
  end

  def destroy
    @post = Post.find_by_id(params[:id])
    @post.destroy
    redirect_to child_posts_url(@post.child)
  end

  def index
    @child = Child.find_by_id(params[:child_id])
    @posts = @child.posts.order('created_at DESC').paginate(page: params[:page], per_page: 10)
    render :index
  end

  private

  def post_params
    params.require('post').permit(:user_id, :child_id, :content, :picture)
  end

  def require_owner!
    post = Post.find_by_id(params[:id])
    unless current_user.id == post.user_id
      redirect_to child_posts_url(post.child_id)
    end
  end
end

app/views/posts/_form.html.erb
<% if @post.persisted? %>
  <% action_url = post_url(@post) %>
  <% button_text = "Edit Post" %>
  <% user_id = @post.user_id %>
  <% method = "patch" %>
<% else %>
  <% action_url = posts_url %>
  <% button_text = "Create Post" %>
  <% user_id = current_user.id %>
  <% @post.child_id ||= params[:child_id] %>
  <% method = "post" %>
<% end %>
<h1> <%= button_text %></h1>

<%= form_for :post, :html => {:multipart => true}, :url => action_url, :method => method do |f| %>
  <%= f.hidden_field :child_id, value: @post.child_id %>
  <%= f.hidden_field :user_id, value: user_id %>
  <p>
    <%= f.label :content %><br />
    <%= f.text_area(:content, cols: 40, rows:10) %>
  </p>
  <p>
    <% if @post.persisted? %>
      <%= f.hidden_field :picture, value: @post.picture %>
    <% else %>
      <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
    <% end %>
  </p>
  <p><%= f.submit %></p>
<% end %>

<% if current_user.id == @post.user_id && @post.persisted? %>
  <p><%= link_to "Delete Post", post_url(@post), method: :delete %></p>
<% end %>

<% child = @post.child %>
<%= link_to "Return to #{child.name}'s posts", child_posts_url(child), method: :get %>

<script type="text/javascript">
  $('#post_picture').bind('change', function() {
    size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/posts/edit.html.erb
<%= render partial: "form" %>

app/views/posts/index.html.erb
<%= link_to "#{@child.name}'s Profile", child_url(@child), method: :get %>
<h1><%= @child.name %></h1>
<p><%= button_to "Add Post", new_child_post_url(@child), method: :get %></p>
<%= will_paginate @posts %>
<% @posts.each do |post| %>
  <h3><%= image_tag post.picture.url %></h3>
  <h3>Content: <%= post.content %></h3>
  <p><%= link_to "View Post", post_url(post) %></p>
  <% if current_user.id == post.user_id %>
    <p><%= link_to "Edit Post", edit_child_post_url(@child.id, post.id) %></p>
  <% end %>
<% end %>
<%= will_paginate @posts %>

app/views/posts/new.html.erb
<%= render partial: "form" %>

app/views/posts/show.html.erb
<h3>Content: <%= @post.content %></h3>
<h3><%= image_tag @post.picture.url %></h3>
<% if @post.user_id == current_user.id %>
  <p> <%= link_to "Edit post", edit_child_post_url(@post.child_id, @post.id), method: :get %></p>
  <p> <%= link_to "Delete post", post_url(@post.id), method: :delete %></p>
<% end %>

<p><%= link_to "Return to #{@post.child.name}'s posts", child_posts_url(@post.child) %></p>